export type Player = {
    ID: number;
    Nome: string;
    Cognome: string;
    DOB: Date;
    Età: number;
    Nazionalità: string;
    Altezza: number | null;
    Peso: number | null;
    Posiz: string;
    Piede: string | null;
    PiedeDebole: string | null;
    Squadra: string | null;
    XP: number | null;
    WROff: number | null;
    WRDef: number | null;
    OVR: number | null;
    POR: number | null;
    DIF: number | null;
    CEN: number | null;
    MEN: number | null;
    ATT: number | null;
    FIS: number | null;
    CPZ: number | null;
    RIFP: number | null;
    PREP: number | null;
    TUFP: number | null;
    POSP: number | null;
    RINP: number | null;
    MARC: number | null;
    CONT: number | null;
    AGGR: number | null;
    SCIV: number | null;
    INTR: number | null;
    PASC: number | null;
    PASL: number | null;
    CRSS: number | null;
    CTRP: number | null;
    VISI: number | null;
    EFFT: number | null;
    POTN: number | null;
    PIAZ: number | null;
    PTIR: number | null;
    TIRD: number | null;
    DRBL: number | null;
    TIRV: number | null;
    TSTA: number | null;
    FINA: number | null;
    ACCL: number | null;
    VELO: number | null;
    RESI: number | null;
    FRZA: number | null;
    AGIL: number | null;
    ELEV: number | null;
    RIFL: number | null;
    EQLB: number | null;
    PNIZ: number | null;
    CRIG: number | null;
    MABI: number | null;
    Tratti: string | null;
    RuoloInCampo: string | null;
};